export function getDefaultPrompts() {
  const now = new Date().toISOString();
  return [
    {
      id: crypto.randomUUID(),
      title: "IBP Demand Sensing — Weekly Consensus",
      body: "In IBP, show me the demand sensing run for the current week. Highlight any statistical forecast deviations greater than 15% and summarize the top three SKUs driving the variance in the EMEA region.",
      body_fr: null,
      notes: "Use in the S&OP consensus meeting demo",
      storyFlow: "Plan-to-Inventory",
      solutions: ["IBP"],
      landscapes: [],
      tags: ["demand", "consensus", "EMEA"],
      isFavorite: true,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "S/4HANA Purchase Order Exception Review",
      body: "Show me all purchase orders in S/4HANA that are overdue by more than 5 days and have a net value above €50,000. Group them by supplier and highlight the top 3 at-risk deliveries.",
      body_fr: null,
      notes: "Great for Procure-to-Pay story opening",
      storyFlow: "Procure-to-Pay",
      solutions: ["S/4HANA"],
      landscapes: [],
      tags: ["PO", "exception", "supplier"],
      isFavorite: true,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "Joule — Summarize Open Sales Orders",
      body: "Summarize all open sales orders for customer ACME Corp that have a requested delivery date within the next 14 days. List them by priority and flag any with inventory shortages.",
      body_fr: null,
      notes: "Use with Joule in S/4HANA Order-to-Cash flow",
      storyFlow: "Order-to-Cash",
      solutions: ["Joule", "S/4HANA"],
      landscapes: [],
      tags: ["sales", "delivery", "Joule"],
      isFavorite: true,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "Ariba — Supplier Risk Assessment",
      body: "In SAP Business Network, identify suppliers in the Electronics category with a risk score above 70. Show their on-time delivery rate for the last 6 months and any active compliance issues.",
      body_fr: null,
      notes: "",
      storyFlow: "Procure-to-Pay",
      solutions: ["Ariba"],
      landscapes: [],
      tags: ["supplier", "risk", "compliance"],
      isFavorite: false,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "IBP Supply Planning — Constrained Run",
      body: "Run a supply planning simulation in IBP with the current demand plan, applying capacity constraints for the Frankfurt DC. Show me where we have shortfalls in the next 8 weeks and which products are most impacted.",
      body_fr: null,
      notes: "Slide 3 of Plan-to-Inventory story deck",
      storyFlow: "Plan-to-Inventory",
      solutions: ["IBP"],
      landscapes: [],
      tags: ["supply", "capacity", "simulation"],
      isFavorite: false,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "S/4HANA — Goods Receipt Discrepancy Report",
      body: "Show me all goods receipts in the last 30 days where the received quantity differs from the purchase order quantity by more than 10%. List the vendor, material, plant, and delta quantity.",
      body_fr: null,
      notes: "",
      storyFlow: "Procure-to-Pay",
      solutions: ["S/4HANA"],
      landscapes: [],
      tags: ["GR", "discrepancy", "receiving"],
      isFavorite: false,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "Joule Studio — Custom AR Skill",
      body: "Design a Joule skill that retrieves the top 5 overdue accounts receivable items for a given customer, formatted as a summary card showing invoice number, amount, days overdue, and contact person.",
      body_fr: null,
      notes: "Demo for Joule Studio extensibility",
      storyFlow: "Record-to-Report",
      solutions: ["Joule Studio"],
      landscapes: [],
      tags: ["skill", "extensibility", "AR"],
      isFavorite: false,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "BTP — Integration Flow Monitoring",
      body: "In SAP Integration Suite, show all integration flows that failed in the last 24 hours. Group by error type and display the top 3 flows by failure count with their retry status.",
      body_fr: null,
      notes: "",
      storyFlow: "Design-to-Operate",
      solutions: ["BTP"],
      landscapes: [],
      tags: ["integration", "monitoring", "errors"],
      isFavorite: false,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "Datasphere — Supply Chain KPI Dashboard",
      body: "Create a view in SAP Datasphere combining inventory turnover ratio, perfect order rate, and days of supply across all EMEA plants for the current fiscal quarter. Include trend lines versus prior year.",
      body_fr: null,
      notes: "",
      storyFlow: "Plan-to-Inventory",
      solutions: ["Datasphere"],
      landscapes: [],
      tags: ["KPI", "dashboard", "analytics"],
      isFavorite: false,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: crypto.randomUUID(),
      title: "End-to-End: P2P Exception to PO Amendment",
      body: "Walk me through a scenario where a goods receipt triggers an invoice discrepancy in Ariba, escalates to a buyer in S/4HANA, and Joule drafts a purchase order amendment — showing the full Procure-to-Pay exception handling flow.",
      body_fr: null,
      notes: "Full E2E story closer — use last in demo",
      storyFlow: "Procure-to-Pay",
      solutions: ["S/4HANA", "Ariba", "Joule"],
      landscapes: [],
      tags: ["E2E", "exception", "amendment"],
      isFavorite: true,
      usageCount: 0,
      lastUsedAt: null,
      attachments: [],
      createdAt: now,
      updatedAt: now
    }
  ];
}
